#!/usr/bin/env bash

# This script is executed by /usr/share/ditana/wayland-sessions/niri-ditana.desktop,
# whose directory is referenced by /etc/greetd/config.toml.

exec > >(systemd-cat -t ditana-pre-niri-login -p info) 2>&1

uwsm stop || true

# /usr/lib/ditana/session-setup is composed of the following kdl entries:
# - login-scripts
# - login-commands
# - first-login-scripts
# - first-login-commands
source /usr/lib/ditana/session-setup

env | sort
journalctl --user -b -u graphical-session.target --no-pager

uwsm start niri.desktop
