#!/usr/bin/env bash

# This script is executed by /usr/share/ditana/xsessions/xfce-ditana.desktop,
# whose directory is referenced by /etc/greetd/config.toml.

{
    export XDG_SESSION_TYPE=x11
    export XDG_SESSION_DESKTOP=xfce
    export XDG_CURRENT_DESKTOP=XFCE

    while read -r line; do
        [[ -z "$line" ]] || [[ "${line:0:1}" = "#" ]] && continue
        export "${line?}"
    done < <(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)

    dbus-update-activation-environment --systemd --all

    # /usr/lib/ditana/session-setup is composed of the following kdl entries:
    # - login-scripts
    # - login-commands
    # - first-login-scripts
    # - first-login-commands
    source /usr/lib/ditana/session-setup

    env | sort
} 2>&1 | systemd-cat -t ditana-pre-xfce-login -p info

if [ -n "$XDG_VTNR" ]; then
    exec startxfce4 -- "vt$XDG_VTNR" -keeptty
else
    exec startxfce4
fi
